### PR TITLE
Feature Add Old Apple website clone

### PR DESCRIPTION
**Pull request by Temmarie**
In this project, I made a clone of the Old Apple webpage (http://archive.fo/UW4oR) using floats, positions and flex.
Here is the [Live Demo](https://raw.githack.com/Temmarie/Apple-clone/feature/index.html)

### CODE REVIEW

**Comment by Temmarie** [comment]
## Building with Backgrounds and Gradients
In this project, I made a clone of the old Apple website using HTML 5 and CSS3. 
I have validated the HTML and CSS files, and I'm now submitting for a review. I look forward to receiving feedback.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Temmarie     
#### Great Job so far, but there are a few more things required. 
### Footer
- [ ] Please align the footer links to look like the original.
### Original  Version


### Your  Version 




### Make changes and submit another code review request.
*Happy coding*

**Comment by Temmarie** [comment]
## Building with Backgrounds and Gradients- Apple clone
- aligned the footer to look like original
- changed from a section tag to a div tag to align the bottom section to look like the original. I made this change in order to get rid of the empty h6 tag I initially kept to remove the  HTML validator warning of having a section header.
-  [Live Demo](https://raw.githack.com/Temmarie/Apple-clone/feature/index.html)

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved ✈️ 

Hi @Temmarie, you did great making the changes requested by the previous reviewer. **Congratulations** your project has been approved. 👍 You can now go ahead and merge to master and submit the project completion form 😄 

Good luck with your next project 💯 
Happy coding 💻 
Daniel Larbi Addo

**Pull request merged**
